linters:
  enable-all: true
  disable:
    - scopelint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - golint # deprecated
    - exhaustivestruct
    - paralleltest
linters-settings:
  varnamelen:
    min-name-length: 1
  wrapcheck:
    ignoreSigRegexps:
      - \.New.*Error\( # default
      - json\.Marshal.*\( # ignore json.Marshal or json.MarshalIndent
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
