linters:
  enable-all: true
  disable:
    - scopelint
    - interfacer
    - maligned
    - golint
linters-settings:
  varnamelen:
    min-name-length: 1
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
